### ISSUE TITLE
TranslatedFieldWithFallback questions

### ISSUE THREAD

**Issue by raratiru** [matthiask/django-translated-fields#13]
I have two questions regarding translated_fields.utils.TranslatedFieldWithFallback:

1. 
    ```

    class MyModel(models.Model):
        name = TranslatedFieldWithFallback(
            models.CharField(max_length=55, blank=True),
        )
        surname = TranslatedFieldWithFallback(
            models.CharField(max_length=55),
        )

    ```
If the default language is 'en' an error will raise when `surname_en` is empty. 

However, if `name_en` (which can be blank) is empty and `name_<another_language>` is not empty, the fallback value will be `None` although  in another language, a value may exist. 

Is this an intended behaviour?

2) 
    https://github.com/matthiask/django-translated-fields/blob/07d0a7aac3b8df507ee19adf12ce16d211fcbf1c/translated_fields/utils.py#L10-L14

    Instead of `settings.LANGUAGES[0][0]` [`LANGUAGE_CODE`](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-LANGUAGE_CODE) wouldn't it be more straightforward?

    **Update**
    `LANGUAGE_CODE` may not be the best option since it defaults to 'en-us' and not just 'en'.

**Comment by gabn88** [comment]
Hi! 

I'm answering regarding 1. because I had something similar. I just created my own fallback_to_default function and used that as attrgetter=fallback_to_default on the TranslatedField function that is defined on the ModelField. This fallback_to_default is equal to modeltranslations (go through all languages) in functionality:

```
def fallback_to_default(name):
    def getter(self):
        value = getattr(
            self,
            to_attribute(name),
        )
        if value:
            return value
        else:
            for language in settings.SELECTABLE_LANGUAGES:
                new_value = getattr(self, to_attribute(name, language))
                if new_value:
                    return new_value
        return value
    return getter
```
Hope it helps!

**Comment by matthiask** [comment]
Thanks @gabn88!

Re 1.

At first I wasn't sure whether the concept of a default language even has its place in this library because it's a bit arbitrary. After copy-pasting the same fallback code into a handful of projects I remembered that practicality beats purity (https://www.python.org/dev/peps/pep-0020/)

It is the intended behavior to only fall back to the primary language, yes. If you require a value you should pass a field to the `TranslatedFieldWithFallback` constructor with `blank=False`. The first language's field will be required then and all other fields will be optional.

If the behavior of `TranslatedFieldWithFallback` is insufficient for your requirements I encourage you to implement your own getter (as @gabn88 did) and/or even add your own `TranslatedField` subclass in the spirit of `TranslatedFieldWithFallback` to your project. Or maybe contribute it back, but I'm not too fond of the [fallback languages mechanism](https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/settings.py#L33) in django-modeltranslation -- it's a bit too flexible for my taste.

You write that errors are raised if `surname_en` is empty. I hope you mean validation errors and not other types of exceptions? But yes, if it's about validation errors then that's intentional (see above)

Re 2.

You wrote it yourself, in many projects `LANGUAGES[0][0] != LANGUAGE_CODE` (en-us vs en is a good example, we often have de-ch vs de in our projects). If we only use the `LANGUAGES` setting (or the `languages` argument to `TranslatedField`) then we have a single source of truth.

**Comment by raratiru** [comment]
> You write that errors are raised if `surname_en` is empty. I hope you mean validation errors and not other types of exceptions?

Yes indeed, they are validation errors, expected because the field is not supposed to be blank. 

The solution provided by @gabn88 is a sweet spot because it springs from the main functionality of this library (no need to override any `clean` method), it is neat and simple!

> If we only use the `LANGUAGES` setting (or the `languages` argument to `TranslatedField`) then we have a single source of truth.

Thank you!

**Comment by raratiru** [comment]
Finally, I decided to give a shot to the first language before start looping around the remaining languages, as such:

```python
def fallback_to_default(name):
    def getter(self):
        value = getattr(
            self,
            to_attribute(name),
        ) or getattr(
            self,
            to_attribute(name, settings.SELECTABLE_LANGUAGES[0]),  
                                           # ^ Arbitrary setting like ['en', 'fr'] 
        )
        if value:
            return value
        else:
            for language in settings.SELECTABLE_LANGUAGES[1:]:
                value = getattr(self, to_attribute(name, language))
                if value:
                    return value
        return value
    return getter
```
