### ISSUE TITLE
Admin - Language ID not visible on readonly fields

### ISSUE THREAD

**Issue by cristianocca** [matthiask/django-translated-fields#18]
If a field is readonly (just a label), the additional Field[lang] label is not added when using TranslatedFieldAdmin.

For example:

```
class ObjectLogAdmin(TranslatedFieldAdmin, admin.ModelAdmin):
    
    # All readonly
    def get_readonly_fields(self, request, obj=None):
        return [field.name for field in self.opts.local_fields]

```

**Comment by matthiask** [comment]
Yes, that's by design. The fields' `verbose_name` attribute is not changed so that e.g. when you create a form containing translated fields you do not have to override the fields' labels again to remove the language code.

Maybe there is a way to make the `TranslatedFieldAdmin` add language codes to readonly fields. I suspect that this would require us to create callables with an appropriate `short_description` for each field and put the callables both in `fieldsets` and `readonly_fields`. We do a similar thing for `list_display` already (https://github.com/matthiask/django-translated-fields/blob/3d6176645dfdbcda39fc854d5ec42203a0b42fca/translated_fields/admin.py#L14-L33) but there it's less effort and -- because of this -- also less ugly.

**Comment by cristianocca** [comment]
I agree that the verbose_name should not be changed, but I would expect that at least on the admin the field label behaves the same regardless of if it is readonly or not. Right now the admin UI ends up rendering the same field twice with the exact same name.

**Comment by matthiask** [comment]
Oh, it shouldn't be the same field. Those should be two distinct fields, one per language, albeit with the same name.

It is a bug but I'm not 100% positive it's worth fixing since a fix might be intrusive.
