### ISSUE TITLE
Must explicit declare fields in every language in Admin

### ISSUE THREAD

**Issue by johncpang** [matthiask/django-translated-fields#3]
The package works fine IFF I don't declare `fields` nor `fieldsets` in my `admin.py`.  In that case, ModelAdmin will properly include "name_en", "name_de", "name_fr" (three actual fields found in database).

If I declare `fields` (or `fieldsets`, for example, to properly group different fields) and use "name" instead of "name_xx", the server returns errors: 

    FieldError at /admin/marketplace/category/1/change/
    Unknown field(s) (name) specified for Category. Check fields/fieldsets/exclude attributes of class CategoryAdmin.

Here is my "settings.py" which declare 3 languages as in example:

```python
LANGUAGE_CODE = 'en'
LANGUAGES = [('en', 'English'), ('de', 'German'), ('fr', 'French')]
```

My "models.py", for simplicity, I only include on translated field.  The actual model I tested has two translate fields (name and short_name), and other support fields (is_active, remarks, created_at, modified_at etc).

```python
class Category(models.Model):
    name = TranslatedField(
        models.CharField(max_length=100, help_text=_("Display name."))
    )
```

My "admin.py".  It works just fine before adding `TranslatedFieldAdmin`.

```python
@admin.register(models.Category)
class CategoryAdmin(TranslatedFieldAdmin, SortableAdminMixin, admin.ModelAdmin):
    fieldsets = (
        (None, {
            'fields': ('id')
        }),
        (_('Details'), {
            'fields': ('name',)
        }),
    )
    add_fieldsets = (
        (None, {
            'fields': ('name',)
        }),
    )
    list_display = ('name', )
    search_fields = ['name', ]
    readonly_fields = ['id', ]

    def get_fieldsets(self, request, obj=None):
        if not obj:
            return self.add_fieldsets
        return super().get_fieldsets(request, obj)
```

Furthermore, when the listing admin still works, the fields "name" is no longer sortable.  It acts if it's a calculated fields.  If I change `list_display= ('name_en')` then sorting is back.

If I change `name` to `name_en` in fields and field sets, it works, but the labels become "Name en [en]".

**Comment by matthiask** [comment]
Yes, that is because the `TranslatedField` class creates a real model field per language, but, as you write, the `name` field itself isn't a field at all, "just" a property of the model.

django-modeltranslation automatically processes declared fieldsets, and expands occurrences of translated fields into their language-specific variants. We could do this too in `TranslatedFieldAdmin`, but I'm not sure we should. It's the sort of magic that's easy to implement at first but leads to maintenance pain down the road (see https://github.com/matthiask/django-translated-fields/#model-admin-support and https://github.com/matthiask/django-translated-fields/#other-features ). So in a way it's intentional that you can't just specify `name`. This also lets you decide whether you want some translated fields in a single row (`fieldsets = [(None, {"fields": [("name_en", "name_de", ...)]})]`) or below each other (`fieldsets = [(None, {"fields": ["name_en", "name_de", ...]})]`)

Also with the ordering. If you want to order by the name fields' value in the current language, add this:

```
from translated_fields.fields import to_attribute

class AdminThingy(admin.ModelAdmin):
   # ...
   def get_ordering(self, request):
       return [to_attribute("name")]
```

Or maybe you'd always like to sort entries by their english name to keep things consistent, so you'd be fine with `ordering = ["name_en"]`


The "Name en [en]" thing comes from you not setting the name fields' `verbose_name`. If you set `name = models.CharField(verbose_name=_("name"), max_length=100, help_text=...)` then all fields' labels would be "name" in the administration interface and you wouldn't know which field belongs to which language. That's why `TranslatedFieldsAdmin` appends the `[<language code>]` suffix to all fields' labels. And that's literally [all it does](https://github.com/matthiask/django-translated-fields/blob/master/translated_fields/admin.py).

**Comment by matthiask** [comment]
Addendum: the list of field names is available as an attribute on the descriptor, so maybe you could also do this to avoid repetition:

```
@admin.register(models.Category)
class CategoryAdmin(TranslatedFieldAdmin, SortableAdminMixin, admin.ModelAdmin):
    fieldsets = (
        (None, {
            'fields': ['id']
        }),
        (_('Details'), {
            'fields': [*models.Category.name.fields],
        }),
    )
```

**Comment by johncpang** [comment]
Thanks @matthiask for your explanation.  One of the important code missing from the document (or I didn't find it in README) is the capability to include all language variants: `[*MODEL.FIELD_NAME.fields]`.  This should be included in the README.

In most of the demo code, the ModelAdmin has empty body (indicate include every fields).  But in real-world, we might use `fieldsets =` to group similar fields, hide private fields, and add property (for calculated results).  Or we use `fields =` to ensure the order of fields in Admin. 

In DRF, we also declare `fields` to explicitly include fields to expose over API.  I prefer not to use `exclude` because I might accidentally expose (newly added) private fields.

**Comment by matthiask** [comment]
Yes, I tried pointing towards the docs but noticed that the `fields` attribute wasn't there at all :)

**Comment by matthiask** [comment]
I added a few examples, hopefully they are useful:
https://github.com/matthiask/django-translated-fields#model-admin-support

(Checking again I saw that the `fields` attribute is documented, but showing how it might be used is very helpful -- https://github.com/matthiask/django-translated-fields#translatedfield-instance-api)

**Comment by johncpang** [comment]
Yes, it was my fault.  I failed to realize the importance of verbose name here.  Usually, I don't add verbose name if it match with the field itself.  Thanks for your help.

**Comment by matthiask** [comment]
You're welcome! I added a note to the `TranslatedFieldAdmin` documentation underlining the importance of setting `verbose_name`.

I always set `verbose_name` because the main language of my clients (and mine as well) isn't english. So it didn't even occur to me that this might happen.
