### ISSUE TITLE
default value for null language

### ISSUE THREAD

**Issue by ahmedsafadii** [matthiask/django-translated-fields#31]
Is it possible to return the default language in case any field had a null value?

again thank you for your great effort.

**Comment by ahmedsafadii** [comment]
Thank you for answering,

I couldn't implement that, i try but i keep getting errors

```
class WeatherGroup(models.Model):
    code = models.CharField(max_length=255, blank=False, null=True, verbose_name=_("Code"))
    name = TranslatedField(
        models.CharField(max_length=255, blank=False, null=True, verbose_name=_("Name"))
    )
```

any chance ?

**Comment by ahmedsafadii** [comment]
```
    name = TranslatedField(
        models.CharField(max_length=255, blank=False, null=True, verbose_name=_("Name")),
        attrgetter=fallback_to_default,
    )
```

is it working but i don't know if it's correct?

**Comment by matthiask** [comment]
The latter does look like it does what you mean it to. 

I just don't know if everything does what it should. The combination of `blank=False` (the Django admin panel requires you to enter values) and `null=True` doesn't make much sense to me **if you're using the Django admin to enter values**

Also, Django discourages against using `null=True` with `CharField`, because now you have two ways of storing empty values, `None` and `""`. 

But if that's what you want you'll be fine.

**Comment by ahmedsafadii** [comment]
Will you are right if I'm using a web app, but since this is coming from mobile side, so it can be null 

blank works only for the JS frontend side I think.

and yes the default value is working like charm now.

thank you
