### ISSUE TITLE
Requesting version bump on PyPI

### ISSUE THREAD

**Issue by jacklinke** [matthiask/django-translated-fields#35]
@matthiask 

I am being a total hypocrite here - I am *very* behind on updating my own packages, so I really hope this doesn't come across as pushy, because I know how much time, effort, and mental energy these seemingly simple things take.

There are some valid reasons to consider pushing a new release of django-translated-fields to PyPI:

- There have been almost 20 commits since version 0.12.0 was pushed to PyPI. While most don't affect the package itself (changes to tests, action, configuration files, etc), the sum of them surely contains enough work to warrant a version bump.
- The updates you have made do not reflect on PyPI. For instance, pyproject.toml was updated to add classifiers for Python 3.11 and 3.12, but that is not yet reflected on the package info page on PyPI. The change to the docs in April was very helpful, and while someone going to the repo will see it, anyone looking at the PyPI page will not. You've put a lot of work into the package, and continue to do so, but from the perspective of someone visiting PyPI to assess which translation package to use, it looks like the project has stagnated.
- **And the selfish reason**: I *really* like this package and want to use it as a dependency for another django package I'm developing, but it doesn't feel right to introduce a 3rd party dependency that 'has not been updated in over 2 years' (despite the fact that I *know* it works as-is with current versions of Django, and that development has continued on the package).

If there is anything blocking a new release that I could help with, please let me know and I will gladly work on a PR I am capable of resolving the blocker.

*(And thanks for a great translation package - it has made a great deal of my work easier and has made my application better!)*

**Comment by matthiask** [comment]
@jacklinke Don't worry! Thanks for reporting this. I have released 0.13 just now.

To be honest, I only looked at changes to the `translated_fields/*` folder and I thought that since basically nothing changed in the code of the package a release wouldn't really matter. But you're of course correct, no releases for such a long time does raise a few questions.

I really wish there was a good way to declare the maintenance status of packages other than activity such as this, I wrote about that here: https://406.ch/writing/managing-complexity-and-technical-debt-by-releasing-open-source-software/ ; django-translated-fields is definitely "1. Actively maintained, used in multiple projects"
